/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d0daf0',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d9e3f9',
        'on-surface': '#121c2c',
        'on-surface-variant': '#3e494a',
        'inverse-surface': '#273141',
        'inverse-on-surface': '#ebf1ff',
        outline: '#6f797a',
        'outline-variant': '#bec8ca',
        'surface-tint': '#006972',
        primary: '#00535b',
        'on-primary': '#ffffff',
        'primary-container': '#006d77',
        'on-primary-container': '#9becf7',
        'inverse-primary': '#82d3de',
        secondary: '#236863',
        'on-secondary': '#ffffff',
        'secondary-container': '#a9ece5',
        'on-secondary-container': '#286d67',
        tertiary: '#434c4f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5b6467',
        'on-tertiary-container': '#d8e1e4',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#9ff0fb',
        'primary-fixed-dim': '#82d3de',
        'on-primary-fixed': '#001f23',
        'on-primary-fixed-variant': '#004f56',
        'secondary-fixed': '#acefe7',
        'secondary-fixed-dim': '#90d3cb',
        'on-secondary-fixed': '#00201e',
        'on-secondary-fixed-variant': '#00504b',
        'tertiary-fixed': '#dbe4e7',
        'tertiary-fixed-dim': '#bfc8cb',
        'on-tertiary-fixed': '#141d1f',
        'on-tertiary-fixed-variant': '#3f484b',
        background: '#f9f9ff',
        'on-background': '#121c2c',
        'surface-variant': '#d9e3f9'
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px'
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px'
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif']
      }
    },
  },
  plugins: [],
}
